# Data Mining Lab 2
#### Team 2:  Patricia Goresen, Jeffrey Lancon, Brychan Manry, George Sturrock

## Introduction
The source of baseball data for this lab is the Sean Lahman Baseball Database [ http://www.seanlahman.com/baseball-archive/statistics/]. Often cited as the most complete baseball database, the data set includes twenty-seven data tables and millions of records covering most non-proprietary baseball data pertaining to offense, fielding, pitching, payroll, player demographics, team statistics, manager data and much more. In past assignments, this team has focused on team level data.  For this Lab, the team will focus on player level data.  In particular, the focus will be on position players.  Pitchers will not be viewed in this study.  This will allow for more exploration of baseball data and provide a broader variety of regression and classification scenarios.  

This lab will focus on the analysis of four specific tables containing player level details in the Lahman Baseball Database:  Batting, Fielding, Player Awards and Salaries.  The names of the different tables accurately describe the contents.  For example, the Batting table contains offensive statics per year for each player.  The tables are at different grains.  The utlimate intention is to have a single dataframe accurately combining all relevant features of the four tables.  The methods used to achieve this goal will be presented below.  

In this Lab, the team will focus on two predictive tasks.  First, models will be trained to predict the salary of a player.  Second, a classification models will be created to attempt to categorize players by position using attributes other than position.  Three different models will be created for each predictive task.

## Data Preparation - Part 1
### Import Data

In [1]:
import pandas as pd
import numpy as np

awards = pd.read_csv('~/7331_Lab2/data/AwardsPlayers.csv')
batting = pd.read_csv('~/7331_Lab2/data/Batting.csv')
fielding = pd.read_csv('~/7331_Lab2/data/Fielding.csv')
salaries = pd.read_csv('~/7331_Lab2/data/Salaries.csv')

print('Awards', awards.info())
print('Batting', batting.info())
print('Fielding', fielding.info())
print('Salaries', salaries.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6158 entries, 0 to 6157
Data columns (total 6 columns):
playerID    6158 non-null object
awardID     6158 non-null object
yearID      6158 non-null int64
lgID        6158 non-null object
tie         47 non-null object
notes       4710 non-null object
dtypes: int64(1), object(5)
memory usage: 288.7+ KB
Awards None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104324 entries, 0 to 104323
Data columns (total 24 columns):
playerID     104324 non-null object
yearID       104324 non-null int64
stint        104324 non-null int64
teamID       104324 non-null object
lgID         103586 non-null object
G            104324 non-null int64
G_batting    0 non-null float64
AB           104324 non-null int64
R            104324 non-null int64
H            104324 non-null int64
2B           104324 non-null int64
3B           104324 non-null int64
HR           104324 non-null int64
RBI          103568 non-null float64
SB           101956 non-null float64
CS           80832 non-null float64
BB           104324 non-null int64
SO           97974 non-null float64
IBB          67722 non-null float64
HBP          101507 non-null float64
SH           98255 non-null float64
SF           68259 non-null float64
GIDP         78921 non-null float64
G_old        0 non-null float64
dtypes: float64(11), int64(10), object(3)
memory usage: 19.1+ MB
Batting None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138838 entries, 0 to 138837
Data columns (total 18 columns):
playerID    138838 non-null object
yearID      138838 non-null int64
stint       138838 non-null int64
teamID      138838 non-null object
lgID        137325 non-null object
POS         138838 non-null object
G           138838 non-null int64
GS          88096 non-null float64
InnOuts     102314 non-null float64
PO          138838 non-null int64
A           138838 non-null int64
E           138837 non-null float64
DP          138838 non-null int64
PB          11351 non-null float64
WP          1169 non-null float64
SB          7906 non-null float64
CS          7906 non-null float64
ZR          1169 non-null float64
dtypes: float64(8), int64(6), object(4)
memory usage: 19.1+ MB
Fielding None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26428 entries, 0 to 26427
Data columns (total 5 columns):
yearID      26428 non-null int64
teamID      26428 non-null object
lgID        26428 non-null object
playerID    26428 non-null object
salary      26428 non-null int64
dtypes: int64(2), object(3)
memory usage: 1.0+ MB
Salaries None

In [2]:
## Go back and convert to table ##
#teamNullCols = pd.DataFrame({'n Missing' : teamNullCols, '% Missing' : ((teamNullCols / teams2.shape[0])*100).round(2)#.astype(str) + "%"})

print("Shape of DataFrames:", "Awards:", awards.shape, "Batting:", batting.shape, "Fielding:", fielding.shape, "Salaries:", salaries.shape)

Shape of DataFrames: Awards: (6158, 6) Batting: (104324, 24) Fielding: (138838, 18) Salaries: (26428, 5)

### Subsetting by Year

As can be seen above, a one to one match does not exist between the four source tables.  The process of creating dataframes which can be merged into a single dataframe will begin with row level filtering.  Only records from the 1985 season and greater will be used for analysis in this assignment.  1985 was chosen for two reasons.  First, salary data only goes back to 1985.  Second, the evolution of the game and it players has changed quite a bit since beginning of the professional game of baseball.  Selecting only records from the 1985 season and forward providees a 32 year data set while eliminating data that would likely lead to erroneous results.

In [3]:
awards = awards[awards.yearID > 1984]
batting = batting[batting.yearID > 1984]
fielding = fielding[fielding.yearID > 1984]
salaries = salaries[salaries.yearID > 1984]

print("Shape of DataFrames:", "Awards:", awards.shape, "Batting:", batting.shape, "Fielding:", fielding.shape, "Salaries:", salaries.shape)

Shape of DataFrames: Awards: (2398, 6) Batting: (42071, 24) Fielding: (54560, 18) Salaries: (26428, 5)

### Batting

The Batting table will be the driver for the overall consolidated data frame.  In other words, fielding, salaries and awards will be merged into the Batting data frame.  First, categorical variables such as Team and League ID which offer limited predictive or structural value will be dropped from the data frame.  The G_old column is missing values in every row and will be dropped as well.

In [4]:
batting = batting.drop(['teamID', 'lgID', 'G_old', 'G_batting', 'stint'], axis=1)
#Drop rows with no basic statistics are recorded in a year
batting = batting[(batting[['AB', 'BB']] != 0).all(axis=1)]
print(batting.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22527 entries, 53 to 104305
Data columns (total 19 columns):
playerID    22527 non-null object
yearID      22527 non-null int64
G           22527 non-null int64
AB          22527 non-null int64
R           22527 non-null int64
H           22527 non-null int64
2B          22527 non-null int64
3B          22527 non-null int64
HR          22527 non-null int64
RBI         22527 non-null float64
SB          22527 non-null float64
CS          22527 non-null float64
BB          22527 non-null int64
SO          22527 non-null float64
IBB         22527 non-null float64
HBP         22527 non-null float64
SH          22527 non-null float64
SF          22527 non-null float64
GIDP        22527 non-null float64
dtypes: float64(9), int64(9), object(1)
memory usage: 3.4+ MB
None

In [5]:
#df = batting.groupby(['playerID', 'yearID']).count().reset_index()
#print(df)

There are approximately 1300 instances remaining where a player has more than one record per year in the batting data frame.  This is to be expected as player trades and multiple stints in the major league do occurr in a single season.  These instances will be consolidated into a single row.

In [6]:
#Identify Instances where a player has more than one batting record per year.
df = batting.groupby(['playerID', 'yearID']).count().reset_index()
df = df[df.G > 1]
print(df)

#Consolidate and Aggreagate
print(batting.groupby(['yearID', 'playerID']).sum().reset_index())
battingFinal = batting.groupby(['yearID', 'playerID']).sum().reset_index()

### Good Code Save for Future ###
#aggRules = {'stint':['count'], 'G':['sum'], 'AB':['sum'], 'R':['sum'], 'H':['sum'], '2B':['sum'], '3B':['sum'], 'HR':['sum'], \
#            'RBI':['sum'], 'SB':['sum'], 'CS':['sum'], 'BB':['sum'], 'SO':['sum'], 'IBB':['sum'], 'HBP':['sum'], 'SH':['sum'], \
#           'SF':['sum'],'GIDP':['sum']}
#
#battingFinal = batting.groupby(['playerID', 'yearID']).agg(aggRules).reset_index()

print(battingFinal)
print(battingFinal.info())
print(battingFinal.describe())

        playerID  yearID  G  AB  R  H  2B  3B  HR  RBI  SB  CS  BB  SO  IBB  \
11     abbotku01    1998  2   2  2  2   2   2   2    2   2   2   2   2    2
26     abnersh01    1991  2   2  2  2   2   2   2    2   2   2   2   2    2
38     abreubo01    2006  2   2  2  2   2   2   2    2   2   2   2   2    2
44     abreubo01    2012  2   2  2  2   2   2   2    2   2   2   2   2    2
67     ackledu01    2015  2   2  2  2   2   2   2    2   2   2   2   2    2
80     adamsma01    2017  2   2  2  2   2   2   2    2   2   2   2   2    2
107    agbaybe01    2002  2   2  2  2   2   2   2    2   2   2   2   2    2
112    aguaylu01    1988  2   2  2  2   2   2   2    2   2   2   2   2    2
141    aldremi01    1991  2   2  2  2   2   2   2    2   2   2   2   2    2
145    aldremi01    1996  2   2  2  2   2   2   2    2   2   2   2   2    2
148    alexama02    1997  2   2  2  2   2   2   2    2   2   2   2   2    2
168    alfoned01    2006  2   2  2  2   2   2   2    2   2   2   2   2    2
196    allenbr01    2011  2   2  2  2   2   2   2    2   2   2   2   2    2
203    allendu01    2000  2   2  2  2   2   2   2    2   2   2   2   2    2
207    allenje01    1998  3   3  3  3   3   3   3    3   3   3   3   3    3
214    almonab01    2014  2   2  2  2   2   2   2    2   2   2   2   2    2
215    almonab01    2015  2   2  2  2   2   2   2    2   2   2   2   2    2
220    almonbi01    1987  2   2  2  2   2   2   2    2   2   2   2   2    2
241    alomaro01    2003  2   2  2  2   2   2   2    2   2   2   2   2    2
242    alomaro01    2004  2   2  2  2   2   2   2    2   2   2   2   2    2
256    alomasa02    2002  2   2  2  2   2   2   2    2   2   2   2   2    2
267    alonsyo01    2017  2   2  2  2   2   2   2    2   2   2   2   2    2
298    alvarga01    2000  2   2  2  2   2   2   2    2   2   2   2   2    2
349    amezaal01    2011  2   2  2  2   2   2   2    2   2   2   2   2    2
350    anderbr01    1988  2   2  2  2   2   2   2    2   2   2   2   2    2
372    anderbr03    2009  2   2  2  2   2   2   2    2   2   2   2   2    2
412    anderjo03    2009  2   2  2  2   2   2   2    2   2   2   2   2    2
426    anderma02    2006  2   2  2  2   2   2   2    2   2   2   2   2    2
427    anderma02    2007  2   2  2  2   2   2   2    2   2   2   2   2    2
445    andresh01    1999  2   2  2  2   2   2   2    2   2   2   2   2    2
...          ...     ... ..  .. .. ..  ..  ..  ..  ...  ..  ..  ..  ..  ...
20713  winnihe01    1988  2   2  2  2   2   2   2    2   2   2   2   2    2
20727   winnra01    2005  2   2  2  2   2   2   2    2   2   2   2   2    2
20732   winnra01    2010  2   2  2  2   2   2   2    2   2   2   2   2    2
20743   wisede01    2012  2   2  2  2   2   2   2    2   2   2   2   2    2
20765   wolfra02    2008  2   2  2  2   2   2   2    2   2   2   2   2    2
20779  womacto01    2003  2   2  2  2   2   2   2    2   2   2   2   2    2
20782  womacto01    2006  2   2  2  2   2   2   2    2   2   2   2   2    2
20792   woodal02    2015  2   2  2  2   2   2   2    2   2   2   2   2    2
20839  woodwch01    2009  2   2  2  2   2   2   2    2   2   2   2   2    2
20856  worthcr01    1995  2   2  2  2   2   2   2    2   2   2   2   2    2
20877  wrighge03    1986  2   2  2  2   2   2   2    2   2   2   2   2    2
20896  wynnema01    1989  2   2  2  2   2   2   2    2   2   2   2   2    2
20924  youklke01    2012  2   2  2  2   2   2   2    2   2   2   2   2    2
20944  youngch04    2014  2   2  2  2   2   2   2    2   2   2   2   2    2
20953  youngde03    2011  2   2  2  2   2   2   2    2   2   2   2   2    2
20955  youngde03    2013  2   2  2  2   2   2   2    2   2   2   2   2    2
20980  younger01    1997  2   2  2  2   2   2   2    2   2   2   2   2    2
20986  younger01    2003  2   2  2  2   2   2   2    2   2   2   2   2    2
20989  younger01    2006  2   2  2  2   2   2   2    2   2   2   2   2    2
21002  younger03    2013  2   2  2  2   2   2   2    2   2   2   2   2    2
21036  youngmi01    1988  2   2  2  2   2   2   2    2   2   2   2   2    2
21050  youngmi02    2013  2   2  2  2   2   2   2    2   2   2   2   2    2
21071   zaungr01    1996  2   2  2  2   2   2   2    2   2   2   2   2    2
21078   zaungr01    2003  2   2  2  2   2   2   2    2   2   2   2   2    2
21084   zaungr01    2009  2   2  2  2   2   2   2    2   2   2   2   2    2
21093  zeileto01    1995  2   2  2  2   2   2   2    2   2   2   2   2    2
21094  zeileto01    1996  2   2  2  2   2   2   2    2   2   2   2   2    2
21096  zeileto01    1998  3   3  3  3   3   3   3    3   3   3   3   3    3
21101  zeileto01    2003  2   2  2  2   2   2   2    2   2   2   2   2    2
21138  zobribe01    2015  2   2  2  2   2   2   2    2   2   2   2   2    2

       HBP  SH  SF  GIDP
11       2   2   2     2
26       2   2   2     2
38       2   2   2     2
44       2   2   2     2
67       2   2   2     2
80       2   2   2     2
107      2   2   2     2
112      2   2   2     2
141      2   2   2     2
145      2   2   2     2
148      2   2   2     2
168      2   2   2     2
196      2   2   2     2
203      2   2   2     2
207      3   3   3     3
214      2   2   2     2
215      2   2   2     2
220      2   2   2     2
241      2   2   2     2
242      2   2   2     2
256      2   2   2     2
267      2   2   2     2
298      2   2   2     2
349      2   2   2     2
350      2   2   2     2
372      2   2   2     2
412      2   2   2     2
426      2   2   2     2
427      2   2   2     2
445      2   2   2     2
...    ...  ..  ..   ...
20713    2   2   2     2
20727    2   2   2     2
20732    2   2   2     2
20743    2   2   2     2
20765    2   2   2     2
20779    2   2   2     2
20782    2   2   2     2
20792    2   2   2     2
20839    2   2   2     2
20856    2   2   2     2
20877    2   2   2     2
20896    2   2   2     2
20924    2   2   2     2
20944    2   2   2     2
20953    2   2   2     2
20955    2   2   2     2
20980    2   2   2     2
20986    2   2   2     2
20989    2   2   2     2
21002    2   2   2     2
21036    2   2   2     2
21050    2   2   2     2
21071    2   2   2     2
21078    2   2   2     2
21084    2   2   2     2
21093    2   2   2     2
21094    2   2   2     2
21096    3   3   3     3
21101    2   2   2     2
21138    2   2   2     2

[1317 rows x 19 columns]
       yearID   playerID    G   AB    R    H  2B  3B  HR    RBI    SB    CS  \
0        1985  adamsri02   54  121   12   23   3   1   2   10.0   1.0   1.0
1        1985  aguaylu01   91  165   27   46   7   3   6   21.0   1.0   0.0
2        1985  aguilri01   22   36    1   10   2   0   0    2.0   0.0   0.0
3        1985  aikenwi01   12   20    2    4   1   0   1    5.0   0.0   0.0
4        1985  almonbi01   88  244   33   66  17   0   6   29.0  10.0   7.0
5        1985  anderda02   77  221   24   44   6   0   4   18.0   5.0   4.0
6        1985  andujjo01   38   94    2   10   2   0   0    8.0   3.0   1.0
7        1985  armasto01  103  385   50  102  17   5  23   64.0   0.0   0.0
8        1985  ashbyal01   65  189   20   53   8   0   8   25.0   0.0   0.0
9        1985  ayalabe01   46   76   10   19   7   0   2   15.0   0.0   0.0
10       1985  backmwa01  145  520   77  142  24   5   1   38.0  30.0  12.0
11       1985  bailema01  114  332   47   88  14   0  10   45.0   0.0   2.0
12       1985  bailobo01   74  118    8   29   3   1   0    7.0   1.0   0.0
13       1985  baineha01  160  640   86  198  29   3  22  113.0   1.0   1.0
14       1985  bakerdu01  111  343   48   92  15   1  14   52.0   2.0   1.0
15       1985  balbost01  160  600   74  146  28   2  36   88.0   1.0   1.0
16       1985  bandoch01   73  173   11   24   4   1   0   13.0   0.0   1.0
17       1985  bannial01   57  122   17   32   4   1   1    6.0   8.0   2.0
18       1985  barfije01  155  539   94  156  34   9  27   84.0  22.0   8.0
19       1985  barrema02  156  534   59  142  26   0   5   56.0   7.0   5.0
20       1985   basske01  150  539   72  145  27   5  16   68.0  19.0   8.0
21       1985  baylodo01  142  477   70  110  24   1  23   91.0   0.0   4.0
22       1985  bedrost01   37   64    3    5   0   0   0    1.0   0.0   0.0
23       1985   bellbu01  151  560   61  128  28   5  10   68.0   3.0   3.0
24       1985   bellge02  157  607   87  167  28   6  28   95.0  21.0   6.0
25       1985  benedbr01   70  208   12   42   6   0   0   20.0   0.0   1.0
26       1985  beniqju01  132  411   54  125  13   5   8   42.0   4.0   3.0
27       1985  bentobu01   31   67    5   12   4   0   0    7.0   0.0   0.0
28       1985  bergmda01   69  140    8   25   2   0   3    7.0   0.0   0.0
29       1985  bernato01  153  500   73  137  26   3  11   59.0  17.0   9.0
...       ...        ...  ...  ...  ...  ...  ..  ..  ..    ...   ...   ...
21130    2017  wachami01   30   46    3    2   0   0   0    3.0   0.0   0.0
21131    2017   wadety01   30   58    7    9   4   0   0    2.0   1.0   1.0
21132    2017  wainwad01   26   42    7   11   2   0   2   11.0   0.0   0.0
21133    2017  walkech02   11   12    2    3   1   0   2    2.0   0.0   0.0
21134    2017  walkene01  111  385   59  102  21   2  14   49.0   0.0   2.0
21135    2017  walketa01   28   52    6   12   1   0   1    5.0   0.0   0.0
21136    2017  weavelu01   15   19    2    3   0   0   0    1.0   0.0   0.0
21137    2017  weeksri01   37   97   13   21   6   0   2    8.0   1.0   0.0
21138    2017  wendljo01    8   13    3    4   1   0   1    5.0   0.0   0.0
21139    2017  werthja01   70  252   35   57  10   1  10   29.0   4.0   3.0
21140    2017  wheelza01   18   27    1    2   1   0   0    0.0   0.0   0.0
21141    2017  whitety01   22   61    7   17   6   0   3   10.0   0.0   1.0
21142    2017  wietema01  123  422   43   95  20   0  10   52.0   1.0   0.0
21143    2017  willima07    5   16    3    4   0   0   0    1.0   2.0   0.0
21144    2017  willima08   28   68    8   16   2   0   3    6.0   1.0   1.0
21145    2017  willini01   83  313   45   90  14   4  12   55.0   1.0   2.0
21146    2017  willitr01   31   41    1    2   0   0   0    0.0   0.0   0.0
21147    2017  winkeje01   47  121   21   36   7   0   7   15.0   1.0   1.0
21148    2017  wolteto01   83  229   30   55   8   1   0   16.0   0.0   1.0
21149    2017   wongko01  108  354   55  101  27   3   4   42.0   8.0   2.0
21150    2017   woodal02   27   52    1    3   0   0   0    4.0   0.0   0.0
21151    2017  woodrbr01    8   10    2    2   0   0   0    0.0   0.0   0.0
21152    2017  yelicch01  156  602  100  170  36   2  18   81.0  16.0   2.0
21153    2017  youngch04   90  243   30   57  12   2   7   25.0   3.0   2.0
21154    2017  younger03   47  110   24   29   5   0   4   16.0  12.0   3.0
21155    2017  zagunma01    7   14    0    0   0   0   0    1.0   2.0   0.0
21156    2017  zimmebr01  101  299   41   72  15   2   8   39.0  18.0   1.0
21157    2017  zimmery01  144  524   90  159  33   0  36  108.0   1.0   0.0
21158    2017  zobribe01  128  435   58  101  20   3  12   50.0   2.0   2.0
21159    2017  zuninmi01  124  387   52   97  25   0  25   64.0   1.0   0.0

       BB     SO   IBB   HBP    SH    SF  GIDP
0       5   23.0   3.0   1.0   3.0   0.0   2.0
1      22   26.0   5.0   6.0   4.0   3.0   7.0
2       1    5.0   0.0   0.0   7.0   0.0   1.0
3       3    6.0   0.0   0.0   0.0   1.0   1.0
4      22   61.0   0.0   1.0   4.0   3.0   6.0
5      35   42.0   3.0   1.0   4.0   1.0   4.0
6       5   50.0   0.0   0.0   7.0   0.0   2.0
7      18   90.0   4.0   2.0   0.0   5.0  14.0
8      24   27.0   2.0   1.0   1.0   1.0   9.0
9       4   17.0   1.0   0.0   0.0   1.0   2.0
10     36   72.0   1.0   1.0  14.0   3.0   3.0
11     67   70.0  13.0   1.0   1.0   1.0  16.0
12      3    5.0   0.0   1.0   8.0   0.0   3.0
13     42   89.0   8.0   1.0   0.0  10.0  23.0
14     50   47.0   0.0   0.0   0.0   3.0  12.0
15     52  166.0   4.0   5.0   0.0   5.0  14.0
16     22   21.0   0.0   0.0   2.0   2.0   6.0
17     14   17.0   0.0   0.0   1.0   0.0   1.0
18     66  143.0   5.0   4.0   0.0   3.0  14.0
19     56   50.0   3.0   2.0  12.0   4.0  14.0
20     31   63.0   1.0   6.0   4.0   2.0  10.0
21     52   90.0   6.0  24.0   1.0  10.0  10.0
22      1   22.0   0.0   0.0   6.0   0.0   0.0
23     67   48.0   3.0   1.0   1.0   6.0  24.0
24     43   90.0   6.0   8.0   0.0   8.0   8.0
25     22   12.0   1.0   1.0   4.0   2.0   8.0
26     34   46.0   3.0   5.0   9.0   1.0  16.0
27      3    9.0   2.0   0.0   1.0   2.0   1.0
28     14   15.0   0.0   0.0   1.0   2.0   6.0
29     69   72.0   2.0   1.0   5.0   4.0  11.0
...    ..    ...   ...   ...   ...   ...   ...
21130   1   22.0   0.0   0.0   7.0   1.0   2.0
21131   5   19.0   0.0   0.0   0.0   0.0   2.0
21132   1   15.0   0.0   0.0   7.0   0.0   2.0
21133   1    5.0   0.0   2.0   0.0   0.0   0.0
21134  55   77.0   2.0   5.0   1.0   2.0   9.0
21135   1   19.0   0.0   0.0   1.0   0.0   1.0
21136   1    9.0   0.0   0.0   3.0   0.0   0.0
21137  12   49.0   0.0   3.0   0.0   0.0   0.0
21138   1    3.0   1.0   0.0   0.0   0.0   0.0
21139  35   69.0   1.0   1.0   0.0   1.0   4.0
21140   1   12.0   0.0   0.0   1.0   0.0   0.0
21141   4   16.0   0.0   1.0   0.0   1.0   0.0
21142  38   94.0   4.0   1.0   0.0   4.0  14.0
21143   1    2.0   0.0   0.0   0.0   0.0   0.0
21144   5   25.0   1.0   0.0   0.0   0.0   2.0
21145  20   97.0   0.0   6.0   0.0   4.0   8.0
21146   2   17.0   0.0   0.0   4.0   0.0   1.0
21147  15   24.0   0.0   0.0   1.0   0.0   2.0
21148  33   55.0   9.0   2.0   2.0   0.0   9.0
21149  41   60.0  11.0  12.0   1.0   3.0   4.0
21150   2   29.0   0.0   0.0   4.0   0.0   1.0
21151   1    2.0   0.0   0.0   1.0   0.0   0.0
21152  80  137.0   4.0   6.0   0.0   6.0  13.0
21153  30   55.0   0.0   2.0   0.0   1.0   4.0
21154   5   31.0   0.0   7.0   3.0   0.0   0.0
21155   4    6.0   0.0   0.0   0.0   0.0   0.0
21156  26   99.0   1.0   4.0   0.0   3.0   5.0
21157  44  126.0   1.0   3.0   0.0   5.0  16.0
21158  54   71.0   2.0   2.0   2.0   3.0  13.0
21159  39  160.0   0.0   8.0   0.0   1.0   8.0

[21160 rows x 19 columns]

       yearID   playerID    G   AB    R    H  2B  3B  HR    RBI    SB    CS  \
0        1985  adamsri02   54  121   12   23   3   1   2   10.0   1.0   1.0
1        1985  aguaylu01   91  165   27   46   7   3   6   21.0   1.0   0.0
2        1985  aguilri01   22   36    1   10   2   0   0    2.0   0.0   0.0
3        1985  aikenwi01   12   20    2    4   1   0   1    5.0   0.0   0.0
4        1985  almonbi01   88  244   33   66  17   0   6   29.0  10.0   7.0
5        1985  anderda02   77  221   24   44   6   0   4   18.0   5.0   4.0
6        1985  andujjo01   38   94    2   10   2   0   0    8.0   3.0   1.0
7        1985  armasto01  103  385   50  102  17   5  23   64.0   0.0   0.0
8        1985  ashbyal01   65  189   20   53   8   0   8   25.0   0.0   0.0
9        1985  ayalabe01   46   76   10   19   7   0   2   15.0   0.0   0.0
10       1985  backmwa01  145  520   77  142  24   5   1   38.0  30.0  12.0
11       1985  bailema01  114  332   47   88  14   0  10   45.0   0.0   2.0
12       1985  bailobo01   74  118    8   29   3   1   0    7.0   1.0   0.0
13       1985  baineha01  160  640   86  198  29   3  22  113.0   1.0   1.0
14       1985  bakerdu01  111  343   48   92  15   1  14   52.0   2.0   1.0
15       1985  balbost01  160  600   74  146  28   2  36   88.0   1.0   1.0
16       1985  bandoch01   73  173   11   24   4   1   0   13.0   0.0   1.0
17       1985  bannial01   57  122   17   32   4   1   1    6.0   8.0   2.0
18       1985  barfije01  155  539   94  156  34   9  27   84.0  22.0   8.0
19       1985  barrema02  156  534   59  142  26   0   5   56.0   7.0   5.0
20       1985   basske01  150  539   72  145  27   5  16   68.0  19.0   8.0
21       1985  baylodo01  142  477   70  110  24   1  23   91.0   0.0   4.0
22       1985  bedrost01   37   64    3    5   0   0   0    1.0   0.0   0.0
23       1985   bellbu01  151  560   61  128  28   5  10   68.0   3.0   3.0
24       1985   bellge02  157  607   87  167  28   6  28   95.0  21.0   6.0
25       1985  benedbr01   70  208   12   42   6   0   0   20.0   0.0   1.0
26       1985  beniqju01  132  411   54  125  13   5   8   42.0   4.0   3.0
27       1985  bentobu01   31   67    5   12   4   0   0    7.0   0.0   0.0
28       1985  bergmda01   69  140    8   25   2   0   3    7.0   0.0   0.0
29       1985  bernato01  153  500   73  137  26   3  11   59.0  17.0   9.0
...       ...        ...  ...  ...  ...  ...  ..  ..  ..    ...   ...   ...
21130    2017  wachami01   30   46    3    2   0   0   0    3.0   0.0   0.0
21131    2017   wadety01   30   58    7    9   4   0   0    2.0   1.0   1.0
21132    2017  wainwad01   26   42    7   11   2   0   2   11.0   0.0   0.0
21133    2017  walkech02   11   12    2    3   1   0   2    2.0   0.0   0.0
21134    2017  walkene01  111  385   59  102  21   2  14   49.0   0.0   2.0
21135    2017  walketa01   28   52    6   12   1   0   1    5.0   0.0   0.0
21136    2017  weavelu01   15   19    2    3   0   0   0    1.0   0.0   0.0
21137    2017  weeksri01   37   97   13   21   6   0   2    8.0   1.0   0.0
21138    2017  wendljo01    8   13    3    4   1   0   1    5.0   0.0   0.0
21139    2017  werthja01   70  252   35   57  10   1  10   29.0   4.0   3.0
21140    2017  wheelza01   18   27    1    2   1   0   0    0.0   0.0   0.0
21141    2017  whitety01   22   61    7   17   6   0   3   10.0   0.0   1.0
21142    2017  wietema01  123  422   43   95  20   0  10   52.0   1.0   0.0
21143    2017  willima07    5   16    3    4   0   0   0    1.0   2.0   0.0
21144    2017  willima08   28   68    8   16   2   0   3    6.0   1.0   1.0
21145    2017  willini01   83  313   45   90  14   4  12   55.0   1.0   2.0
21146    2017  willitr01   31   41    1    2   0   0   0    0.0   0.0   0.0
21147    2017  winkeje01   47  121   21   36   7   0   7   15.0   1.0   1.0
21148    2017  wolteto01   83  229   30   55   8   1   0   16.0   0.0   1.0
21149    2017   wongko01  108  354   55  101  27   3   4   42.0   8.0   2.0
21150    2017   woodal02   27   52    1    3   0   0   0    4.0   0.0   0.0
21151    2017  woodrbr01    8   10    2    2   0   0   0    0.0   0.0   0.0
21152    2017  yelicch01  156  602  100  170  36   2  18   81.0  16.0   2.0
21153    2017  youngch04   90  243   30   57  12   2   7   25.0   3.0   2.0
21154    2017  younger03   47  110   24   29   5   0   4   16.0  12.0   3.0
21155    2017  zagunma01    7   14    0    0   0   0   0    1.0   2.0   0.0
21156    2017  zimmebr01  101  299   41   72  15   2   8   39.0  18.0   1.0
21157    2017  zimmery01  144  524   90  159  33   0  36  108.0   1.0   0.0
21158    2017  zobribe01  128  435   58  101  20   3  12   50.0   2.0   2.0
21159    2017  zuninmi01  124  387   52   97  25   0  25   64.0   1.0   0.0

       BB     SO   IBB   HBP    SH    SF  GIDP
0       5   23.0   3.0   1.0   3.0   0.0   2.0
1      22   26.0   5.0   6.0   4.0   3.0   7.0
2       1    5.0   0.0   0.0   7.0   0.0   1.0
3       3    6.0   0.0   0.0   0.0   1.0   1.0
4      22   61.0   0.0   1.0   4.0   3.0   6.0
5      35   42.0   3.0   1.0   4.0   1.0   4.0
6       5   50.0   0.0   0.0   7.0   0.0   2.0
7      18   90.0   4.0   2.0   0.0   5.0  14.0
8      24   27.0   2.0   1.0   1.0   1.0   9.0
9       4   17.0   1.0   0.0   0.0   1.0   2.0
10     36   72.0   1.0   1.0  14.0   3.0   3.0
11     67   70.0  13.0   1.0   1.0   1.0  16.0
12      3    5.0   0.0   1.0   8.0   0.0   3.0
13     42   89.0   8.0   1.0   0.0  10.0  23.0
14     50   47.0   0.0   0.0   0.0   3.0  12.0
15     52  166.0   4.0   5.0   0.0   5.0  14.0
16     22   21.0   0.0   0.0   2.0   2.0   6.0
17     14   17.0   0.0   0.0   1.0   0.0   1.0
18     66  143.0   5.0   4.0   0.0   3.0  14.0
19     56   50.0   3.0   2.0  12.0   4.0  14.0
20     31   63.0   1.0   6.0   4.0   2.0  10.0
21     52   90.0   6.0  24.0   1.0  10.0  10.0
22      1   22.0   0.0   0.0   6.0   0.0   0.0
23     67   48.0   3.0   1.0   1.0   6.0  24.0
24     43   90.0   6.0   8.0   0.0   8.0   8.0
25     22   12.0   1.0   1.0   4.0   2.0   8.0
26     34   46.0   3.0   5.0   9.0   1.0  16.0
27      3    9.0   2.0   0.0   1.0   2.0   1.0
28     14   15.0   0.0   0.0   1.0   2.0   6.0
29     69   72.0   2.0   1.0   5.0   4.0  11.0
...    ..    ...   ...   ...   ...   ...   ...
21130   1   22.0   0.0   0.0   7.0   1.0   2.0
21131   5   19.0   0.0   0.0   0.0   0.0   2.0
21132   1   15.0   0.0   0.0   7.0   0.0   2.0
21133   1    5.0   0.0   2.0   0.0   0.0   0.0
21134  55   77.0   2.0   5.0   1.0   2.0   9.0
21135   1   19.0   0.0   0.0   1.0   0.0   1.0
21136   1    9.0   0.0   0.0   3.0   0.0   0.0
21137  12   49.0   0.0   3.0   0.0   0.0   0.0
21138   1    3.0   1.0   0.0   0.0   0.0   0.0
21139  35   69.0   1.0   1.0   0.0   1.0   4.0
21140   1   12.0   0.0   0.0   1.0   0.0   0.0
21141   4   16.0   0.0   1.0   0.0   1.0   0.0
21142  38   94.0   4.0   1.0   0.0   4.0  14.0
21143   1    2.0   0.0   0.0   0.0   0.0   0.0
21144   5   25.0   1.0   0.0   0.0   0.0   2.0
21145  20   97.0   0.0   6.0   0.0   4.0   8.0
21146   2   17.0   0.0   0.0   4.0   0.0   1.0
21147  15   24.0   0.0   0.0   1.0   0.0   2.0
21148  33   55.0   9.0   2.0   2.0   0.0   9.0
21149  41   60.0  11.0  12.0   1.0   3.0   4.0
21150   2   29.0   0.0   0.0   4.0   0.0   1.0
21151   1    2.0   0.0   0.0   1.0   0.0   0.0
21152  80  137.0   4.0   6.0   0.0   6.0  13.0
21153  30   55.0   0.0   2.0   0.0   1.0   4.0
21154   5   31.0   0.0   7.0   3.0   0.0   0.0
21155   4    6.0   0.0   0.0   0.0   0.0   0.0
21156  26   99.0   1.0   4.0   0.0   3.0   5.0
21157  44  126.0   1.0   3.0   0.0   5.0  16.0
21158  54   71.0   2.0   2.0   2.0   3.0  13.0
21159  39  160.0   0.0   8.0   0.0   1.0   8.0

[21160 rows x 19 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21160 entries, 0 to 21159
Data columns (total 19 columns):
yearID      21160 non-null int64
playerID    21160 non-null object
G           21160 non-null int64
AB          21160 non-null int64
R           21160 non-null int64
H           21160 non-null int64
2B          21160 non-null int64
3B          21160 non-null int64
HR          21160 non-null int64
RBI         21160 non-null float64
SB          21160 non-null float64
CS          21160 non-null float64
BB          21160 non-null int64
SO          21160 non-null float64
IBB         21160 non-null float64
HBP         21160 non-null float64
SH          21160 non-null float64
SF          21160 non-null float64
GIDP        21160 non-null float64
dtypes: float64(9), int64(9), object(1)
memory usage: 3.1+ MB
None
             yearID             G            AB             R             H  \
count  21160.000000  21160.000000  21160.000000  21160.000000  21160.000000
mean    2001.507845     78.567250    241.614698     32.513658     63.500709
std        9.409878     49.956058    199.172162     31.295678     57.532276
min     1985.000000      1.000000      1.000000      0.000000      0.000000
25%     1994.000000     32.000000     58.000000      5.000000     11.000000
50%     2002.000000     76.000000    190.000000     22.000000     46.000000
75%     2010.000000    125.000000    416.000000     54.000000    110.000000
max     2017.000000    163.000000    716.000000    152.000000    262.000000

                 2B            3B            HR           RBI            SB  \
count  21160.000000  21160.000000  21160.000000  21160.000000  21160.000000
mean      12.251843      1.372732      7.120227     30.824149      4.624433
std       11.873773      2.090482      9.316208     31.238458      8.687104
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        2.000000      0.000000      0.000000      4.000000      0.000000
50%        8.000000      1.000000      3.000000     20.000000      1.000000
75%       20.000000      2.000000     11.000000     50.000000      5.000000
max       59.000000     23.000000     73.000000    165.000000    110.000000

                 CS            BB            SO           IBB           HBP  \
count  21160.000000  21160.000000  21160.000000  21160.000000  21160.000000
mean       1.981711     23.563800     46.011673      1.912476      2.178592
std        3.018915     24.216623     38.416402      3.577106      3.146502
min        0.000000      1.000000      0.000000      0.000000      0.000000
25%        0.000000      4.000000     15.000000      0.000000      0.000000
50%        1.000000     16.000000     35.000000      0.000000      1.000000
75%        3.000000     37.000000     70.000000      2.000000      3.000000
max       29.000000    232.000000    223.000000    120.000000     35.000000

                 SH            SF          GIDP
count  21160.000000  21160.000000  21160.000000
mean       2.112949      2.011011      5.449622
std        3.030338      2.397996      5.556520
min        0.000000      0.000000      0.000000
25%        0.000000      0.000000      1.000000
50%        1.000000      1.000000      4.000000
75%        3.000000      3.000000      9.000000

max       39.000000     17.000000     35.000000

In [7]:
print("Index:", battingFinal.index)
print("Columns:", battingFinal.columns)

Index: RangeIndex(start=0, stop=21160, step=1)
Columns: Index(['yearID', 'playerID', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI',
       'SB', 'CS', 'BB', 'SO', 'IBB', 'HBP', 'SH', 'SF', 'GIDP'],
      dtype='object')

### Fielding
The Fielding table contains most of the common defensive statistics in baseball.  The grain of this table is by player, year, sting and position.  It is common for players to play more than one position over the course of a season (year).  However, most players have a primary position.  There is also the concept of a utlity player.  This a player who has no primary position and plays a significant number of games in many positions.  The end objective is to produce a final fielding file with data summarized at the player and year grain.  As this lab is focused on everyday position players, pitchers will be dropped from the fielding data frame.  As this lab is focused on everyday position players, pitchers will be dropped from the fielding data frame.

In [8]:
fielding = fielding[fielding.POS != 'P']
print(fielding.info())
print(fielding.describe())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33738 entries, 76 to 138819
Data columns (total 18 columns):
playerID    33738 non-null object
yearID      33738 non-null int64
stint       33738 non-null int64
teamID      33738 non-null object
lgID        33738 non-null object
POS         33738 non-null object
G           33738 non-null int64
GS          33727 non-null float64
InnOuts     33727 non-null float64
PO          33738 non-null int64
A           33738 non-null int64
E           33738 non-null float64
DP          33738 non-null int64
PB          3651 non-null float64
WP          0 non-null float64
SB          3651 non-null float64
CS          3651 non-null float64
ZR          0 non-null float64
dtypes: float64(8), int64(6), object(4)
memory usage: 4.9+ MB
None
             yearID         stint             G            GS       InnOuts  \
count  33738.000000  33738.000000  33738.000000  33727.000000  33727.000000
mean    2001.689697      1.077153     41.294297     35.961781    963.608830
std        9.454190      0.282277     47.472854     46.329978   1218.781043
min     1985.000000      1.000000      1.000000      0.000000      0.000000
25%     1994.000000      1.000000      5.000000      2.000000     63.000000
50%     2002.000000      1.000000     19.000000     12.000000    348.000000
75%     2010.000000      1.000000     66.000000     55.000000   1483.000000
max     2017.000000      4.000000    163.000000    162.000000   4388.000000

                 PO             A             E            DP           PB  \
count  33738.000000  33738.000000  33738.000000  33738.000000  3651.000000
mean     117.968641     41.094552      2.693521     10.789733     3.074226
std      211.322068     88.192519      4.272296     24.048724     3.558932
min        0.000000      0.000000      0.000000      0.000000     0.000000
25%        5.000000      1.000000      0.000000      0.000000     0.000000
50%       30.000000      6.000000      1.000000      1.000000     2.000000
75%      141.000000     31.000000      3.000000      7.000000     5.000000
max     1597.000000    570.000000     42.000000    176.000000    35.000000

        WP           SB           CS   ZR
count  0.0  3651.000000  3651.000000  0.0
mean   NaN    26.908244    11.546700  NaN
std    NaN    26.716453    12.345847  NaN
min    NaN     0.000000     0.000000  NaN
25%    NaN     4.000000     1.000000  NaN
50%    NaN    19.000000     8.000000  NaN
75%    NaN    43.000000    18.000000  NaN
max    NaN   155.000000    89.000000  NaN

From the above describe statement, it's easy to see WP (wild pitch) and ZR (zone rating) are missing values in the entire column.  The two columns will be dropped from the fielding data frame.  To maintain consistency with the batting data frame, team and league will be dropped as well.

In [9]:
fielding = fielding.drop(['teamID', 'lgID', 'WP', 'ZR'], axis=1)

There is high rate of missing values in the "PB", "SB" and "CS" columns.  This does make sense as these are statistics specific to catchers.  The data was spot checked to verify these are accurate missing values.  These missing values will be replaced with zeroes.

In [10]:
fielding.fillna(value={'PB': 0, 'SB': 0, 'ZR': 0, 'CS': 0}, inplace = True)
print(fielding.info())
print(fielding.describe())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33738 entries, 76 to 138819
Data columns (total 14 columns):
playerID    33738 non-null object
yearID      33738 non-null int64
stint       33738 non-null int64
POS         33738 non-null object
G           33738 non-null int64
GS          33727 non-null float64
InnOuts     33727 non-null float64
PO          33738 non-null int64
A           33738 non-null int64
E           33738 non-null float64
DP          33738 non-null int64
PB          33738 non-null float64
SB          33738 non-null float64
CS          33738 non-null float64
dtypes: float64(6), int64(6), object(2)
memory usage: 3.9+ MB
None
             yearID         stint             G            GS       InnOuts  \
count  33738.000000  33738.000000  33738.000000  33727.000000  33727.000000
mean    2001.689697      1.077153     41.294297     35.961781    963.608830
std        9.454190      0.282277     47.472854     46.329978   1218.781043
min     1985.000000      1.000000      1.000000      0.000000      0.000000
25%     1994.000000      1.000000      5.000000      2.000000     63.000000
50%     2002.000000      1.000000     19.000000     12.000000    348.000000
75%     2010.000000      1.000000     66.000000     55.000000   1483.000000
max     2017.000000      4.000000    163.000000    162.000000   4388.000000

                 PO             A             E            DP            PB  \
count  33738.000000  33738.000000  33738.000000  33738.000000  33738.000000
mean     117.968641     41.094552      2.693521     10.789733      0.332681
std      211.322068     88.192519      4.272296     24.048724      1.510768
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        5.000000      1.000000      0.000000      0.000000      0.000000
50%       30.000000      6.000000      1.000000      1.000000      0.000000
75%      141.000000     31.000000      3.000000      7.000000      0.000000
max     1597.000000    570.000000     42.000000    176.000000     35.000000

                 SB            CS
count  33738.000000  33738.000000
mean       2.911909      1.249541
std       12.128468      5.418246
min        0.000000      0.000000
25%        0.000000      0.000000
50%        0.000000      0.000000
75%        0.000000      0.000000
max      155.000000     89.000000

In [11]:
#Identify Players who played multiple positions per year.
df = fielding.groupby(['playerID', 'yearID']).count().reset_index()
df = df[df.stint > 1]
print(df)

        playerID  yearID  stint  POS  G  GS  InnOuts  PO  A  E  DP  PB  SB  CS
1       abadan01    2003      2    2  2   2        2   2  2  2   2   2   2   2
7      abbotku01    1993      3    3  3   3        3   3  3  3   3   3   3   3
10     abbotku01    1996      3    3  3   3        3   3  3  3   3   3   3   3
11     abbotku01    1997      4    4  4   4        4   4  4  4   4   4   4   4
12     abbotku01    1998      7    7  7   7        7   7  7  7   7   7   7   7
13     abbotku01    1999      4    4  4   4        4   4  4  4   4   4   4   4
14     abbotku01    2000      4    4  4   4        4   4  4  4   4   4   4   4
15     abbotku01    2001      2    2  2   2        2   2  2  2   2   2   2   2
21     abernbr01    2003      2    2  2   2        2   2  2  2   2   2   2   2
22     abernbr01    2005      2    2  2   2        2   2  2  2   2   2   2   2
27     abnersh01    1991      2    2  2   2        2   2  2  2   2   2   2   2
39     abreubo01    2006      2    2  2   2        2   2  2  2   2   2   2   2
45     abreubo01    2012      2    2  2   2        2   2  2  2   2   2   2   2
51     abreuto01    2007      3    3  3   3        3   3  3  3   3   3   3   3
52     abreuto01    2009      2    2  2   2        2   2  2  2   2   2   2   2
53     abreuto01    2010      3    3  3   3        3   3  3  3   3   3   3   3
54     abreuto01    2012      3    3  3   3        3   3  3  3   3   3   3   3
55     abreuto01    2013      3    3  3   3        3   3  3  3   3   3   3   3
56     abreuto01    2014      2    2  2   2        2   2  2  2   2   2   2   2
57     ackledu01    2011      2    2  2   2        2   2  2  2   2   2   2   2
58     ackledu01    2012      2    2  2   2        2   2  2  2   2   2   2   2
59     ackledu01    2013      3    3  3   3        3   3  3  3   3   3   3   3
61     ackledu01    2015      5    5  5   5        5   5  5  5   5   5   5   5
62     ackledu01    2016      3    3  3   3        3   3  3  3   3   3   3   3
63     adamecr01    2014      2    2  2   2        2   2  2  2   2   2   2   2
64     adamecr01    2015      2    2  2   2        2   2  2  2   2   2   2   2
65     adamecr01    2016      3    3  3   3        3   3  3  3   3   3   3   3
66     adamecr01    2017      3    3  3   3        3   3  3  3   3   3   3   3
67     adamsda02    2013      3    3  3   3        3   3  3  3   3   3   3   3
75     adamsma01    2017      4    4  4   4        4   4  4  4   4   4   4   4
...          ...     ...    ...  ... ..  ..      ...  .. .. ..  ..  ..  ..  ..
19551  zawadla01    2010      3    3  3   3        3   3  3  3   3   3   3   3
19553  zeileto01    1990      4    4  4   4        4   4  4  4   4   4   4   4
19558  zeileto01    1995      4    4  4   4        4   4  4  4   4   4   4   4
19559  zeileto01    1996      3    3  3   3        3   3  3  3   3   3   3   3
19561  zeileto01    1998      4    4  4   4        4   4  4  4   4   4   4   4
19562  zeileto01    1999      2    2  2   2        2   2  2  2   2   2   2   2
19566  zeileto01    2003      3    3  3   3        3   3  3  3   3   3   3   3
19567  zeileto01    2004      3    3  3   3        3   3  3  3   3   3   3   3
19569  zimmery01    2005      2    2  2   2        2   2  2  2   2   2   2   2
19578  zimmery01    2014      3    3  3   3        3   3  3  3   3   3   3   3
19579  zimmery01    2015      2    2  2   2        2   2  2  2   2   2   2   2
19582  zinteal01    2002      2    2  2   2        2   2  2  2   2   2   2   2
19586  zobribe01    2008      4    4  4   4        4   4  4  4   4   4   4   4
19587  zobribe01    2009      5    5  5   5        5   5  5  5   5   5   5   5
19588  zobribe01    2010      4    4  4   4        4   4  4  4   4   4   4   4
19589  zobribe01    2011      2    2  2   2        2   2  2  2   2   2   2   2
19590  zobribe01    2012      3    3  3   3        3   3  3  3   3   3   3   3
19591  zobribe01    2013      3    3  3   3        3   3  3  3   3   3   3   3
19592  zobribe01    2014      3    3  3   3        3   3  3  3   3   3   3   3
19593  zobribe01    2015      5    5  5   5        5   5  5  5   5   5   5   5
19594  zobribe01    2016      4    4  4   4        4   4  4  4   4   4   4   4
19595  zobribe01    2017      4    4  4   4        4   4  4  4   4   4   4   4
19599  zoskyed01    1995      2    2  2   2        2   2  2  2   2   2   2   2
19600  zoskyed01    1999      2    2  2   2        2   2  2  2   2   2   2   2
19602  zuberjo01    1998      2    2  2   2        2   2  2  2   2   2   2   2
19603  zuletju01    2000      2    2  2   2        2   2  2  2   2   2   2   2
19613  zupcibo01    1994      4    4  4   4        4   4  4  4   4   4   4   4
19614  zuvelpa01    1985      3    3  3   3        3   3  3  3   3   3   3   3
19616  zuvelpa01    1987      3    3  3   3        3   3  3  3   3   3   3   3
19618  zuvelpa01    1989      2    2  2   2        2   2  2  2   2   2   2   2

[8023 rows x 14 columns]

In [12]:
#Identify Primary Postion per Player per Year Based on Max Games at a position.
df = fielding.groupby(['playerID', 'yearID', 'POS']).sum().reset_index()
df = df.groupby(['playerID', 'yearID', 'POS'])['G'].max().reset_index()
#df = df.groupby(['playerID', 'yearID', 'POS']).max()['G']
df = df.sort_values(by=['playerID', 'yearID', 'G'], ascending=[True, True, False])
print(df)
print(df.describe())

primePOS = pd.DataFrame()
svPlayerID = ''
svYearID = 0

for index, row in df.iterrows():
    #print (row["playerID"], row["yearID"], row['POS'], row['G'])
    if (svPlayerID != row['playerID'] or svYearID != row['yearID']):
        primePOS = primePOS.append({'playerID': row['playerID'], 'yearID': row['yearID'], 'Primary': row['POS']}, ignore_index=True)
        #print(svPlayerID, row["playerID"], svYearID, row["yearID"], row['POS'], row['G'])
        svPlayerID = row['playerID']
        svYearID = row['yearID']
    else:
        continue

        playerID  yearID POS    G
0       abadan01    2001  1B    1
1       abadan01    2003  1B    7
2       abadan01    2003  OF    1
3      abbotje01    1997  OF   10
4      abbotje01    1998  OF   76
5      abbotje01    1999  OF   17
6      abbotje01    2000  OF   65
7      abbotje01    2001  OF   17
9      abbotku01    1993  OF   13
10     abbotku01    1993  SS    6
8      abbotku01    1993  2B    2
11     abbotku01    1994  SS   99
12     abbotku01    1995  SS  115
15     abbotku01    1996  SS   44
14     abbotku01    1996  3B   33
13     abbotku01    1996  2B   20
16     abbotku01    1997  2B   54
18     abbotku01    1997  OF   10
19     abbotku01    1997  SS    7
17     abbotku01    1997  3B    4
23     abbotku01    1998  SS   35
22     abbotku01    1998  OF   14
20     abbotku01    1998  2B    7
21     abbotku01    1998  3B    4
25     abbotku01    1999  2B   66
24     abbotku01    1999  1B    8
26     abbotku01    1999  OF    4
27     abbotku01    1999  SS    3
31     abbotku01    2000  SS   39
28     abbotku01    2000  2B   23
...          ...     ...  ..  ...
31713  zoskyed01    1999  3B    4
31712  zoskyed01    1999  2B    2
31714  zuberjo01    1996  1B   22
31716  zuberjo01    1998  OF    5
31715  zuberjo01    1998  1B    4
31717  zuletju01    2000  1B   14
31718  zuletju01    2000  OF    6
31719  zuletju01    2001  1B   35
31720  zuninmi01    2013   C   50
31721  zuninmi01    2014   C  130
31722  zuninmi01    2015   C  112
31723  zuninmi01    2016   C   52
31724  zuninmi01    2017   C  120
31725  zupcibo01    1991  OF   16
31726  zupcibo01    1992  OF  114
31727  zupcibo01    1993  OF  122
31730  zupcibo01    1994  OF   30
31729  zupcibo01    1994  3B    2
31728  zupcibo01    1994  1B    1
31731  zuvelpa01    1985  2B   42
31733  zuvelpa01    1985  SS   33
31732  zuvelpa01    1985  3B    5
31734  zuvelpa01    1986  SS   21
31735  zuvelpa01    1987  2B    7
31737  zuvelpa01    1987  SS    6
31736  zuvelpa01    1987  3B    1
31738  zuvelpa01    1988  SS   49
31740  zuvelpa01    1989  SS   15
31739  zuvelpa01    1989  3B    5
31741  zuvelpa01    1991  3B    2

[31742 rows x 4 columns]
             yearID             G
count  31742.000000  31742.000000
mean    2001.604215     43.890965
std        9.476431     48.945115
min     1985.000000      1.000000
25%     1993.000000      5.000000
50%     2002.000000     20.000000
75%     2010.000000     74.000000
max     2017.000000    163.000000

In [13]:
print(primePOS)

      Primary   playerID  yearID
0          1B   abadan01  2001.0
1          1B   abadan01  2003.0
2          OF  abbotje01  1997.0
3          OF  abbotje01  1998.0
4          OF  abbotje01  1999.0
5          OF  abbotje01  2000.0
6          OF  abbotje01  2001.0
7          OF  abbotku01  1993.0
8          SS  abbotku01  1994.0
9          SS  abbotku01  1995.0
10         SS  abbotku01  1996.0
11         2B  abbotku01  1997.0
12         SS  abbotku01  1998.0
13         2B  abbotku01  1999.0
14         SS  abbotku01  2000.0
15         2B  abbotku01  2001.0
16         OF  abercre01  2006.0
17         OF  abercre01  2007.0
18         OF  abercre01  2008.0
19         2B  abernbr01  2001.0
20         2B  abernbr01  2002.0
21         2B  abernbr01  2003.0
22         2B  abernbr01  2005.0
23         OF  abnersh01  1987.0
24         OF  abnersh01  1988.0
25         OF  abnersh01  1989.0
26         OF  abnersh01  1990.0
27         OF  abnersh01  1991.0
28         OF  abnersh01  1992.0
29         OF  abreubo01  1996.0
...       ...        ...     ...
19590      OF  zobribe01  2012.0
19591      2B  zobribe01  2013.0
19592      2B  zobribe01  2014.0
19593      2B  zobribe01  2015.0
19594      2B  zobribe01  2016.0
19595      2B  zobribe01  2017.0
19596      OF  zoccope01  2003.0
19597      SS  zoskyed01  1991.0
19598      SS  zoskyed01  1992.0
19599      SS  zoskyed01  1995.0
19600      3B  zoskyed01  1999.0
19601      1B  zuberjo01  1996.0
19602      OF  zuberjo01  1998.0
19603      1B  zuletju01  2000.0
19604      1B  zuletju01  2001.0
19605       C  zuninmi01  2013.0
19606       C  zuninmi01  2014.0
19607       C  zuninmi01  2015.0
19608       C  zuninmi01  2016.0
19609       C  zuninmi01  2017.0
19610      OF  zupcibo01  1991.0
19611      OF  zupcibo01  1992.0
19612      OF  zupcibo01  1993.0
19613      OF  zupcibo01  1994.0
19614      2B  zuvelpa01  1985.0
19615      SS  zuvelpa01  1986.0
19616      2B  zuvelpa01  1987.0
19617      SS  zuvelpa01  1988.0
19618      SS  zuvelpa01  1989.0
19619      3B  zuvelpa01  1991.0

[19620 rows x 3 columns]

In [14]:
#Condense Fielding Dataframe into one row per player per year.
fielding = fielding.groupby(['playerID', 'yearID']).sum().reset_index()

#Merge Primary Position into condensed Fielding data frame
fieldingFinal = pd.merge(fielding, primePOS, on=['playerID', 'yearID'], how='left')

print(fieldingFinal)
print(fieldingFinal.describe())

        playerID yearID  stint    G     GS  InnOuts    PO    A     E  DP  \
0       abadan01   2001      1    1    0.0      3.0     2    0   0.0   1
1       abadan01   2003      2    8    4.0    135.0    35    1   1.0   2
2      abbotje01   1997      1   10    4.0    140.0    15    0   0.0   0
3      abbotje01   1998      1   76   61.0   1526.0   132    0   4.0   0
4      abbotje01   1999      1   17   17.0    408.0    25    0   1.0   0
5      abbotje01   2000      1   65   50.0   1357.0   101    2   2.0   0
6      abbotje01   2001      1   17    8.0    257.0    26    0   1.0   0
7      abbotku01   1993      3   21   14.0    414.0    36   13   2.0   2
8      abbotku01   1994      1   99   93.0   2476.0   162  260  15.0  61
9      abbotku01   1995      1  115  109.0   2925.0   149  290  19.0  66
10     abbotku01   1996      3   97   83.0   2156.0   123  205  12.0  43
11     abbotku01   1997      4   75   57.0   1491.0   126  136   8.0  27
12     abbotku01   1998     11   60   43.0   1128.0    78   94  12.0  21
13     abbotku01   1999      4   81   69.0   1732.0   188  151   4.0  42
14     abbotku01   2000      4   66   35.0   1122.0    74  105   7.0  13
15     abbotku01   2001      2    2    1.0     30.0     2    8   0.0   0
16     abercre01   2006      1   93   67.0   1862.0   176    3   5.0   1
17     abercre01   2007      1   19   17.0    434.0    60    2   1.0   0
18     abercre01   2008      1   22   12.0    328.0    36    2   0.0   1
19     abernbr01   2001      1   79   78.0   2042.0   150  209   7.0  56
20     abernbr01   2002      1  116  115.0   3045.0   253  316  12.0  85
21     abernbr01   2003      3   11    7.0    229.0    13   28   1.0   4
22     abernbr01   2005      2   22   17.0    466.0    29   37   2.0   9
23     abnersh01   1987      1   14   10.0    300.0    23    2   2.0   1
24     abnersh01   1988      1   35   24.0    679.0    55    1   1.0   1
25     abnersh01   1989      1   51   23.0    734.0    67    0   0.0   0
26     abnersh01   1990      1   62   40.0   1177.0   108    1   1.0   0
27     abnersh01   1991      3   77   54.0   1545.0   158    4   0.0   1
28     abnersh01   1992      1   94   48.0   1544.0   155    2   0.0   0
29     abreubo01   1996      1    7    4.0    105.0     6    0   0.0   0
...          ...    ...    ...  ...    ...      ...   ...  ...   ...  ..
19590  zobribe01   2012      3  176  152.0   4025.0   232  252  12.0  55
19591  zobribe01   2013      3  188  154.0   4130.0   278  373   5.0  79
19592  zobribe01   2014      3  164  137.0   3659.0   222  244   8.0  44
19593  zobribe01   2015      8  122  115.0   2983.0   194  190   7.0  53
19594  zobribe01   2016      4  167  142.0   3795.0   221  251   7.0  52
19595  zobribe01   2017      4  152  105.0   2747.0   188  149   3.0  39
19596  zoccope01   2003      1    7    7.0    171.0    16    0   0.0   0
19597  zoskyed01   1991      1   18    6.0    255.0    12   26   0.0   5
19598  zoskyed01   1992      1    8    1.0     75.0     2   10   1.0   2
19599  zoskyed01   1995      2    5    1.0     41.0     1    2   1.0   1
19600  zoskyed01   1999      2    6    0.0     33.0     1    4   0.0   0
19601  zuberjo01   1996      1   22   20.0    543.0   145   11   2.0  10
19602  zuberjo01   1998      2    9    6.0    159.0    22    1   0.0   1
19603  zuletju01   2000      2   20   13.0    362.0    83    8   3.0   9
19604  zuletju01   2001      1   35   23.0    657.0   213    7   2.0  11
19605  zuninmi01   2013      1   50   48.0   1289.0   363   22   2.0   1
19606  zuninmi01   2014      1  130  125.0   3363.0  1010   84   5.0   5
19607  zuninmi01   2015      1  112  101.0   2759.0   809   44   5.0   6
19608  zuninmi01   2016      1   52   48.0   1331.0   400   15   0.0   0
19609  zuninmi01   2017      1  120  112.0   2982.0   894   56   7.0   5
19610  zupcibo01   1991      1   16    4.0    212.0    14    0   2.0   0
19611  zupcibo01   1992      1  114  100.0   2740.0   241   11   6.0   3
19612  zupcibo01   1993      1  122   72.0   2229.0   179    7   4.0   2
19613  zupcibo01   1994      7   33   22.0    661.0    49    4   0.0   0
19614  zuvelpa01   1985      3   80   49.0   1452.0   112  173   8.0  39
19615  zuvelpa01   1986      1   21   18.0    453.0    30   54   3.0  12
19616  zuvelpa01   1987      3   14    7.0    241.0    20   25   0.0   5
19617  zuvelpa01   1988      1   49   44.0   1139.0    77  112   8.0  21
19618  zuvelpa01   1989      2   20   10.0    301.0    14   24   2.0   1
19619  zuvelpa01   1991      1    2    0.0      6.0     0    0   0.0   0

         PB    SB    CS Primary
0       0.0   0.0   0.0      1B
1       0.0   0.0   0.0      1B
2       0.0   0.0   0.0      OF
3       0.0   0.0   0.0      OF
4       0.0   0.0   0.0      OF
5       0.0   0.0   0.0      OF
6       0.0   0.0   0.0      OF
7       0.0   0.0   0.0      OF
8       0.0   0.0   0.0      SS
9       0.0   0.0   0.0      SS
10      0.0   0.0   0.0      SS
11      0.0   0.0   0.0      2B
12      0.0   0.0   0.0      SS
13      0.0   0.0   0.0      2B
14      0.0   0.0   0.0      SS
15      0.0   0.0   0.0      2B
16      0.0   0.0   0.0      OF
17      0.0   0.0   0.0      OF
18      0.0   0.0   0.0      OF
19      0.0   0.0   0.0      2B
20      0.0   0.0   0.0      2B
21      0.0   0.0   0.0      2B
22      0.0   0.0   0.0      2B
23      0.0   0.0   0.0      OF
24      0.0   0.0   0.0      OF
25      0.0   0.0   0.0      OF
26      0.0   0.0   0.0      OF
27      0.0   0.0   0.0      OF
28      0.0   0.0   0.0      OF
29      0.0   0.0   0.0      OF
...     ...   ...   ...     ...
19590   0.0   0.0   0.0      OF
19591   0.0   0.0   0.0      2B
19592   0.0   0.0   0.0      2B
19593   0.0   0.0   0.0      2B
19594   0.0   0.0   0.0      2B
19595   0.0   0.0   0.0      2B
19596   0.0   0.0   0.0      OF
19597   0.0   0.0   0.0      SS
19598   0.0   0.0   0.0      SS
19599   0.0   0.0   0.0      SS
19600   0.0   0.0   0.0      3B
19601   0.0   0.0   0.0      1B
19602   0.0   0.0   0.0      OF
19603   0.0   0.0   0.0      1B
19604   0.0   0.0   0.0      1B
19605   2.0  28.0   6.0       C
19606   8.0  71.0  28.0       C
19607   6.0  42.0  22.0       C
19608   3.0  19.0   7.0       C
19609  10.0  54.0  17.0       C
19610   0.0   0.0   0.0      OF
19611   0.0   0.0   0.0      OF
19612   0.0   0.0   0.0      OF
19613   0.0   0.0   0.0      OF
19614   0.0   0.0   0.0      2B
19615   0.0   0.0   0.0      SS
19616   0.0   0.0   0.0      2B
19617   0.0   0.0   0.0      SS
19618   0.0   0.0   0.0      SS
19619   0.0   0.0   0.0      3B

[19620 rows x 14 columns]
              stint             G            GS       InnOuts            PO  \
count  19620.000000  19620.000000  19620.000000  19620.000000  19620.000000
mean       1.852243     71.008512     61.818705   1656.454383    202.855556
std        1.485177     52.012431     51.463925   1348.468108    254.791997
min        1.000000      1.000000      0.000000      0.000000      0.000000
25%        1.000000     21.000000     13.000000    384.000000     37.000000
50%        1.000000     65.000000     50.000000   1354.500000    119.000000
75%        2.000000    119.000000    108.000000   2848.000000    258.000000
max       22.000000    195.000000    163.000000   4388.000000   1597.000000

                  A             E            DP            PB            SB  \
count  19620.000000  19620.000000  19620.000000  19620.000000  19620.000000
mean      70.665036      4.631702     18.553721      0.572069      5.007238
std      113.714521      5.275095     30.522851      1.961647     15.748140
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        3.000000      1.000000      1.000000      0.000000      0.000000
50%       14.000000      3.000000      3.000000      0.000000      0.000000
75%       79.000000      7.000000     22.000000      0.000000      0.000000
max      570.000000     42.000000    176.000000     35.000000    155.000000

                 CS
count  19620.000000
mean       2.148675
std        7.032315
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max       89.000000

### Salaries

The Salaries table contains yearly salary figures for players beginning in 1985.  This data will be condensed into one row per player per year similar to the fielding and batting tables.  League and Team will be dropped from this data frame as well.

In [15]:
#Drop League and Team
salaries = salaries.drop(['teamID', 'lgID'], axis=1)

#Summarize salaries at the year and player level
salariesFinal = salaries.groupby(['playerID', 'yearID']).sum().reset_index()

print(salariesFinal)
print(salariesFinal.describe())

        playerID  yearID    salary
0      aardsda01    2004    300000
1      aardsda01    2007    387500
2      aardsda01    2008    403250
3      aardsda01    2009    419000
4      aardsda01    2010   2750000
5      aardsda01    2011   4500000
6      aardsda01    2012    500000
7       aasedo01    1986    600000
8       aasedo01    1987    625000
9       aasedo01    1988    675000
10      aasedo01    1989    400000
11      abadan01    2006    327000
12      abadfe01    2011    418000
13      abadfe01    2012    485000
14      abadfe01    2014    525900
15      abadfe01    2015   1087500
16      abadfe01    2016   1250000
17     abbotje01    1998    175000
18     abbotje01    1999    255000
19     abbotje01    2000    255000
20     abbotje01    2001    300000
21     abbotji01    1989     68000
22     abbotji01    1990    185000
23     abbotji01    1991    357500
24     abbotji01    1992   1850000
25     abbotji01    1993   2350000
26     abbotji01    1994   2775000
27     abbotji01    1995   2775000
28     abbotji01    1996   2200000
29     abbotji01    1999    400000
...          ...     ...       ...
26293   zitoba01    2010  18500000
26294   zitoba01    2011  18500000
26295   zitoba01    2012  19000000
26296   zitoba01    2013  20000000
26297  zobribe01    2007    383400
26298  zobribe01    2008    395800
26299  zobribe01    2009    415900
26300  zobribe01    2010    438100
26301  zobribe01    2011   4687300
26302  zobribe01    2012   4687300
26303  zobribe01    2013   5687300
26304  zobribe01    2014   7000000
26305  zobribe01    2015   7500000
26306  zobribe01    2016  10500000
26307  zoskyed01    1992    109000
26308  zuberjo01    1996    109000
26309  zuletju01    2001    200000
26310  zumayjo01    2006    327000
26311  zumayjo01    2007    410000
26312  zumayjo01    2008    420000
26313  zumayjo01    2009    735000
26314  zumayjo01    2010    915000
26315  zumayjo01    2011   1400000
26316  zuninmi01    2014    504100
26317  zuninmi01    2015    523500
26318  zupcibo01    1991    100000
26319  zupcibo01    1992    109000
26320  zupcibo01    1993    222000
26321  zuvelpa01    1989    145000
26322   zychto01    2016    511000

[26323 rows x 3 columns]
             yearID        salary
count  26323.000000  2.632300e+04
mean    2000.901797  2.093953e+06
std        8.913938  3.460182e+06
min     1985.000000  0.000000e+00
25%     1994.000000  3.000000e+05
50%     2001.000000  5.543910e+05
75%     2009.000000  2.362500e+06
max     2016.000000  3.300000e+07

### Merge Batting, Fielding and Salaries

In [16]:
#Merge Batting and Fielding
#print(pd.merge(battingFinal, fieldingFinal, on=['playerID', 'yearID'], how='left'))
player = pd.merge(battingFinal, fieldingFinal, on=['playerID', 'yearID'], how='left')

#Merge Salaries
player = pd.merge(player, salariesFinal, on=['playerID', 'yearID'], how='left')

print(player)
print(player.info())
print(player.describe())

      yearID   playerID  G_x   AB    R    H  2B  3B  HR    RBI    ...      \
0       1985  adamsri02   54  121   12   23   3   1   2   10.0    ...
1       1985  aguaylu01   91  165   27   46   7   3   6   21.0    ...
2       1985  aguilri01   22   36    1   10   2   0   0    2.0    ...
3       1985  aikenwi01   12   20    2    4   1   0   1    5.0    ...
4       1985  almonbi01   88  244   33   66  17   0   6   29.0    ...
5       1985  anderda02   77  221   24   44   6   0   4   18.0    ...
6       1985  andujjo01   38   94    2   10   2   0   0    8.0    ...
7       1985  armasto01  103  385   50  102  17   5  23   64.0    ...
8       1985  ashbyal01   65  189   20   53   8   0   8   25.0    ...
9       1985  ayalabe01   46   76   10   19   7   0   2   15.0    ...
10      1985  backmwa01  145  520   77  142  24   5   1   38.0    ...
11      1985  bailema01  114  332   47   88  14   0  10   45.0    ...
12      1985  bailobo01   74  118    8   29   3   1   0    7.0    ...
13      1985  baineha01  160  640   86  198  29   3  22  113.0    ...
14      1985  bakerdu01  111  343   48   92  15   1  14   52.0    ...
15      1985  balbost01  160  600   74  146  28   2  36   88.0    ...
16      1985  bandoch01   73  173   11   24   4   1   0   13.0    ...
17      1985  bannial01   57  122   17   32   4   1   1    6.0    ...
18      1985  barfije01  155  539   94  156  34   9  27   84.0    ...
19      1985  barrema02  156  534   59  142  26   0   5   56.0    ...
20      1985   basske01  150  539   72  145  27   5  16   68.0    ...
21      1985  baylodo01  142  477   70  110  24   1  23   91.0    ...
22      1985  bedrost01   37   64    3    5   0   0   0    1.0    ...
23      1985   bellbu01  151  560   61  128  28   5  10   68.0    ...
24      1985   bellge02  157  607   87  167  28   6  28   95.0    ...
25      1985  benedbr01   70  208   12   42   6   0   0   20.0    ...
26      1985  beniqju01  132  411   54  125  13   5   8   42.0    ...
27      1985  bentobu01   31   67    5   12   4   0   0    7.0    ...
28      1985  bergmda01   69  140    8   25   2   0   3    7.0    ...
29      1985  bernato01  153  500   73  137  26   3  11   59.0    ...
...      ...        ...  ...  ...  ...  ...  ..  ..  ..    ...    ...
21130   2017  wachami01   30   46    3    2   0   0   0    3.0    ...
21131   2017   wadety01   30   58    7    9   4   0   0    2.0    ...
21132   2017  wainwad01   26   42    7   11   2   0   2   11.0    ...
21133   2017  walkech02   11   12    2    3   1   0   2    2.0    ...
21134   2017  walkene01  111  385   59  102  21   2  14   49.0    ...
21135   2017  walketa01   28   52    6   12   1   0   1    5.0    ...
21136   2017  weavelu01   15   19    2    3   0   0   0    1.0    ...
21137   2017  weeksri01   37   97   13   21   6   0   2    8.0    ...
21138   2017  wendljo01    8   13    3    4   1   0   1    5.0    ...
21139   2017  werthja01   70  252   35   57  10   1  10   29.0    ...
21140   2017  wheelza01   18   27    1    2   1   0   0    0.0    ...
21141   2017  whitety01   22   61    7   17   6   0   3   10.0    ...
21142   2017  wietema01  123  422   43   95  20   0  10   52.0    ...
21143   2017  willima07    5   16    3    4   0   0   0    1.0    ...
21144   2017  willima08   28   68    8   16   2   0   3    6.0    ...
21145   2017  willini01   83  313   45   90  14   4  12   55.0    ...
21146   2017  willitr01   31   41    1    2   0   0   0    0.0    ...
21147   2017  winkeje01   47  121   21   36   7   0   7   15.0    ...
21148   2017  wolteto01   83  229   30   55   8   1   0   16.0    ...
21149   2017   wongko01  108  354   55  101  27   3   4   42.0    ...
21150   2017   woodal02   27   52    1    3   0   0   0    4.0    ...
21151   2017  woodrbr01    8   10    2    2   0   0   0    0.0    ...
21152   2017  yelicch01  156  602  100  170  36   2  18   81.0    ...
21153   2017  youngch04   90  243   30   57  12   2   7   25.0    ...
21154   2017  younger03   47  110   24   29   5   0   4   16.0    ...
21155   2017  zagunma01    7   14    0    0   0   0   0    1.0    ...
21156   2017  zimmebr01  101  299   41   72  15   2   8   39.0    ...
21157   2017  zimmery01  144  524   90  159  33   0  36  108.0    ...
21158   2017  zobribe01  128  435   58  101  20   3  12   50.0    ...
21159   2017  zuninmi01  124  387   52   97  25   0  25   64.0    ...

       InnOuts      PO      A     E     DP    PB  SB_y  CS_y  Primary  \
0        897.0    35.0  101.0   5.0   13.0   0.0   0.0   0.0       SS
1       1370.0    92.0  158.0   9.0   27.0   0.0   0.0   0.0       SS
2          NaN     NaN    NaN   NaN    NaN   NaN   NaN   NaN      NaN
3          NaN     NaN    NaN   NaN    NaN   NaN   NaN   NaN      NaN
4       1612.0   104.0  108.0   5.0   22.0   0.0   0.0   0.0       SS
5       1702.0    61.0  187.0   9.0   20.0   0.0   0.0   0.0       3B
6          NaN     NaN    NaN   NaN    NaN   NaN   NaN   NaN      NaN
7       1962.0   173.0    3.0   3.0    1.0   0.0   0.0   0.0       OF
8       1414.0   312.0   37.0   8.0    1.0  14.0  58.0  21.0        C
9        294.0    21.0    1.0   2.0    0.0   0.0   0.0   0.0       OF
10      3390.0   273.0  370.0   7.0   76.0   0.0   0.0   0.0       2B
11      2658.0   566.0   52.0  13.0    6.0  19.0  73.0  33.0        C
12       927.0    35.0  103.0   3.0   12.0   0.0   0.0   0.0       3B
13      4193.0   318.0    8.0   2.0    2.0   0.0   0.0   0.0       OF
14      1957.0   465.0   29.0   5.0   33.0   0.0   0.0   0.0       1B
15      4284.0  1573.0  101.0  12.0  138.0   0.0   0.0   0.0       1B
16      1460.0   251.0   28.0   4.0    3.0   3.0  53.0  19.0        C
17       467.0    46.0   18.0   1.0    4.0   0.0   0.0   0.0       OF
18      4071.0   349.0   22.0   4.0    8.0   0.0   0.0   0.0       OF
19      4007.0   355.0  479.0  11.0  110.0   0.0   0.0   0.0       2B
20      3567.0   328.0   10.0   1.0    1.0   0.0   0.0   0.0       OF
21         NaN     NaN    NaN   NaN    NaN   NaN   NaN   NaN      NaN
22         NaN     NaN    NaN   NaN    NaN   NaN   NaN   NaN      NaN
23      3889.0   124.0  297.0  25.0   35.0   0.0   0.0   0.0       3B
24      4134.0   320.0   14.0  11.0    3.0   0.0   0.0   0.0       OF
25      1698.0   314.0   35.0   4.0    1.0   1.0  65.0  24.0        C
26      2469.0   439.0   26.0   4.0   42.0   0.0   0.0   0.0       OF
27       552.0    75.0   13.0   4.0    1.0   5.0  11.0   6.0        C
28       924.0   306.0   25.0   3.0   25.0   0.0   0.0   0.0       1B
29      3619.0   313.0  399.0  16.0   87.0   0.0   0.0   0.0       2B
...        ...     ...    ...   ...    ...   ...   ...   ...      ...
21130      NaN     NaN    NaN   NaN    NaN   NaN   NaN   NaN      NaN
21131    432.0    27.0   20.0   3.0    6.0   0.0   0.0   0.0       2B
21132      NaN     NaN    NaN   NaN    NaN   NaN   NaN   NaN      NaN
21133     27.0    11.0    0.0   1.0    2.0   0.0   0.0   0.0       1B
21134   2671.0   221.0  211.0   7.0   57.0   0.0   0.0   0.0       2B
21135      NaN     NaN    NaN   NaN    NaN   NaN   NaN   NaN      NaN
21136      NaN     NaN    NaN   NaN    NaN   NaN   NaN   NaN      NaN
21137    271.0    70.0    4.0   0.0    8.0   0.0   0.0   0.0       1B
21138     78.0     6.0    7.0   0.0    3.0   0.0   0.0   0.0       2B
21139   1655.0   116.0    1.0   4.0    0.0   0.0   0.0   0.0       OF
21140      NaN     NaN    NaN   NaN    NaN   NaN   NaN   NaN      NaN
21141    426.0   113.0    6.0   3.0   11.0   0.0   0.0   0.0       1B
21142   3011.0  1023.0   43.0   8.0    5.0   5.0  57.0  19.0        C
21143    120.0     7.0    0.0   0.0    0.0   0.0   0.0   0.0       OF
21144    482.0    36.0    1.0   2.0    0.0   0.0   0.0   0.0       OF
21145   2055.0   110.0    4.0   0.0    1.0   0.0   0.0   0.0       OF
21146      NaN     NaN    NaN   NaN    NaN   NaN   NaN   NaN      NaN
21147    658.0    41.0    2.0   1.0    0.0   0.0   0.0   0.0       OF
21148   1786.0   530.0   48.0   2.0    6.0   7.0  22.0  14.0        C
21149   2640.0   191.0  276.0  10.0   78.0   0.0   0.0   0.0       2B
21150      NaN     NaN    NaN   NaN    NaN   NaN   NaN   NaN      NaN
21151      NaN     NaN    NaN   NaN    NaN   NaN   NaN   NaN      NaN
21152   4106.0   370.0    1.0   1.0    0.0   0.0   0.0   0.0       OF
21153   1089.0    65.0    1.0   0.0    1.0   0.0   0.0   0.0       OF
21154    822.0    68.0    1.0   0.0    0.0   0.0   0.0   0.0       OF
21155     96.0     5.0    0.0   0.0    0.0   0.0   0.0   0.0       OF
21156   2093.0   168.0    8.0   0.0    1.0   0.0   0.0   0.0       OF
21157   3486.0  1005.0   49.0  12.0  100.0   0.0   0.0   0.0       1B
21158   2747.0   188.0  149.0   3.0   39.0   0.0   0.0   0.0       2B
21159   2982.0   894.0   56.0   7.0    5.0  10.0  54.0  17.0        C

          salary
0            NaN
1       237000.0
2            NaN
3            NaN
4       255000.0
5            NaN
6      1030000.0
7       915000.0
8       416667.0
9       303333.0
10      200000.0
11           NaN
12      330000.0
13      675000.0
14      575000.0
15      205000.0
16      225000.0
17      350000.0
18      325000.0
19      272500.0
20      155000.0
21      810000.0
22      550000.0
23      751297.0
24      335000.0
25      545000.0
26      365000.0
27           NaN
28      262500.0
29      400000.0
...          ...
21130        NaN
21131        NaN
21132        NaN
21133        NaN
21134        NaN
21135        NaN
21136        NaN
21137        NaN
21138        NaN
21139        NaN
21140        NaN
21141        NaN
21142        NaN
21143        NaN
21144        NaN
21145        NaN
21146        NaN
21147        NaN
21148        NaN
21149        NaN
21150        NaN
21151        NaN
21152        NaN
21153        NaN
21154        NaN
21155        NaN
21156        NaN
21157        NaN
21158        NaN
21159        NaN

[21160 rows x 32 columns]
<class 'pandas.core.frame.DataFrame'>
Int64Index: 21160 entries, 0 to 21159
Data columns (total 32 columns):
yearID      21160 non-null object
playerID    21160 non-null object
G_x         21160 non-null int64
AB          21160 non-null int64
R           21160 non-null int64
H           21160 non-null int64
2B          21160 non-null int64
3B          21160 non-null int64
HR          21160 non-null int64
RBI         21160 non-null float64
SB_x        21160 non-null float64
CS_x        21160 non-null float64
BB          21160 non-null int64
SO          21160 non-null float64
IBB         21160 non-null float64
HBP         21160 non-null float64
SH          21160 non-null float64
SF          21160 non-null float64
GIDP        21160 non-null float64
stint       18051 non-null float64
G_y         18051 non-null float64
GS          18051 non-null float64
InnOuts     18051 non-null float64
PO          18051 non-null float64
A           18051 non-null float64
E           18051 non-null float64
DP          18051 non-null float64
PB          18051 non-null float64
SB_y        18051 non-null float64
CS_y        18051 non-null float64
Primary     18051 non-null object
salary      15816 non-null float64
dtypes: float64(21), int64(8), object(3)
memory usage: 5.3+ MB
None

                G_x            AB             R             H            2B  \
count  21160.000000  21160.000000  21160.000000  21160.000000  21160.000000
mean      78.567250    241.614698     32.513658     63.500709     12.251843
std       49.956058    199.172162     31.295678     57.532276     11.873773
min        1.000000      1.000000      0.000000      0.000000      0.000000
25%       32.000000     58.000000      5.000000     11.000000      2.000000
50%       76.000000    190.000000     22.000000     46.000000      8.000000
75%      125.000000    416.000000     54.000000    110.000000     20.000000
max      163.000000    716.000000    152.000000    262.000000     59.000000

                 3B            HR           RBI          SB_x          CS_x  \
count  21160.000000  21160.000000  21160.000000  21160.000000  21160.000000
mean       1.372732      7.120227     30.824149      4.624433      1.981711
std        2.090482      9.316208     31.238458      8.687104      3.018915
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      4.000000      0.000000      0.000000
50%        1.000000      3.000000     20.000000      1.000000      1.000000
75%        2.000000     11.000000     50.000000      5.000000      3.000000
max       23.000000     73.000000    165.000000    110.000000     29.000000

           ...                 GS       InnOuts            PO             A  \
count      ...       18051.000000  18051.000000  18051.000000  18051.000000
mean       ...          66.988145   1793.651875    219.586560     76.534984
std        ...          50.435053   1319.219176    258.925871    116.704370
min        ...           0.000000      0.000000      0.000000      0.000000
25%        ...          20.000000    573.000000     52.000000      4.000000
50%        ...          57.000000   1555.000000    138.000000     18.000000
75%        ...         112.000000   2974.500000    272.000000     90.500000
max        ...         163.000000   4388.000000   1597.000000    570.000000

                  E            DP            PB          SB_y          CS_y  \
count  18051.000000  18051.000000  18051.000000  18051.000000  18051.000000
mean       5.008088     20.098166      0.615645      5.398482      2.321644
std        5.332464     31.344463      2.036609     16.352361      7.303665
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        1.000000      1.000000      0.000000      0.000000      0.000000
50%        3.000000      4.000000      0.000000      0.000000      0.000000
75%        7.000000     25.000000      0.000000      0.000000      0.000000
max       42.000000    176.000000     35.000000    155.000000     89.000000

             salary
count  1.581600e+04
mean   2.377127e+06
std    3.788210e+06
min    0.000000e+00
25%    3.100000e+05
50%    6.750000e+05
75%    2.800000e+06
max    3.300000e+07

[8 rows x 29 columns]

### Missing Values

### Scaling

#### Write Player CSV file

In [17]:
player.to_csv('~/7331_Lab2/data/player.csv', sep=',', encoding='utf-8')